# Don't print a new line at the start of the prompt
add_newline = false

command_timeout = 2500

[line_break]
disabled = true

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = "â˜ï¸  "

[git_branch]
symbol = "î‚  "
format = "on [$symbol$branch]($style) "

[golang]
disabled = true
format = "using [$symbol$version]($style) "

[nodejs]
disabled = true

[package]
format = "[$symbol$version]($style) "
symbol = "ğŸ“¦ "
