add_newline = false

[line_break]
disabled = true

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 4
truncation_symbol = ""
format = "on [$symbol$branch]($style) "

[git_metrics]
disabled = false
added_style = "bold blue"
format = "[+$added]($added_style)/[-$deleted]($deleted_style) "

[deno]
disabled = false
format = "via [ğŸ¦• $version](green bold) "

[nodejs]
disabled = false
format = "via [ğŸ¤– $version](bold green) "

[rust]
disabled = false
detect_extensions = ["rs"]
detect_files = ["Cargo.toml"]
format = "via [âš™ï¸  $version](red bold) "

[package]
format = "[$symbol$version]($style) "
symbol = "ğŸ“¦ "
